apiVersion: v1
kind: Service
metadata:
  name: sqlserver-headless
  namespace: sqlserver-ha
spec:
  clusterIP: None
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
    name: sql
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: sqlserver-ha
spec:
  type: NodePort
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 31433
    protocol: TCP
    name: sql
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
